//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patici.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class HayvanCin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HayvanCin()
        {
            this.HayvanTurs = new HashSet<HayvanTur>();
        }
    
        public System.Guid Id { get; set; }
        public string Ad { get; set; }
        public bool Sil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HayvanTur> HayvanTurs { get; set; }
    }
}
