//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patici.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class HayvanGaleri
    {
        public System.Guid Id { get; set; }
        public System.Guid HayvanID { get; set; }
        public string Foto { get; set; }
        public Nullable<int> Sira { get; set; }
        public System.DateTime Tarih { get; set; }
        public bool Sil { get; set; }
    
        public virtual Hayvan Hayvan { get; set; }
    }
}
