//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patici.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class HayvanCinsiyet
    {
        public System.Guid Id { get; set; }
        public string Ad { get; set; }
        public bool Sil { get; set; }
    }
}
