//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patici.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class HayvanTur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HayvanTur()
        {
            this.Hayvans = new HashSet<Hayvan>();
            this.OtelTurs = new HashSet<OtelTur>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid HayCinsID { get; set; }
        public string Ad { get; set; }
        public bool Sil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hayvan> Hayvans { get; set; }
        public virtual HayvanCin HayvanCin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtelTur> OtelTurs { get; set; }
    }
}
