//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patici.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hayvan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hayvan()
        {
            this.HayvanGaleris = new HashSet<HayvanGaleri>();
            this.Ilans = new HashSet<Ilan>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid KulDetayID { get; set; }
        public System.Guid TurID { get; set; }
        public System.Guid YasID { get; set; }
        public string Ad { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime Tarih { get; set; }
        public bool Sil { get; set; }
    
        public virtual HayvanTur HayvanTur { get; set; }
        public virtual HayvanYa HayvanYa { get; set; }
        public virtual KullaniciDetay KullaniciDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HayvanGaleri> HayvanGaleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ilan> Ilans { get; set; }
    }
}
