//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patici.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciDetay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KullaniciDetay()
        {
            this.Hayvans = new HashSet<Hayvan>();
            this.Ilans = new HashSet<Ilan>();
            this.Otels = new HashSet<Otel>();
            this.OtelGaleris = new HashSet<OtelGaleri>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid KulID { get; set; }
        public System.Guid TurID { get; set; }
        public Nullable<System.Guid> FiyatID { get; set; }
        public string AdSoyad { get; set; }
        public string ProfilFoto { get; set; }
        public Nullable<bool> Onay { get; set; }
        public string Belge { get; set; }
        public string Aciklama { get; set; }
        public string Website { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
        public System.DateTime Tarih { get; set; }
        public bool Sil { get; set; }
    
        public virtual FiyatAraligi FiyatAraligi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hayvan> Hayvans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ilan> Ilans { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual KullaniciTur KullaniciTur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Otel> Otels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtelGaleri> OtelGaleris { get; set; }
    }
}
